### ISSUE TITLE
`idma_tracer` macro captures `z` instead of actual data on response channel

### ISSUE THREAD

**Issue by Freakness109** [pulp-platform/iDMA#14]
Tried it in questa 2019.3, project was the CVA6 with the patches for the iDMA. Instantiated the tracer guarded by pragma translate_off/on.
Compilation flags did include +acc in the vopt step, but not the vsim.
Manually inserting the macro and replacing the response signals from `i_idma_backend.axi_rsp_i.w_ready/r_valid` to the actual signal names fixed the issue.

**Comment by thommythomaso** [comment]
Thank you for pointing out this issue. Without the `+acc` flag, the simulator is allowed to optimize signals away. This could be the issue. I would keep the current version connecting the backend signals and living with `+acc`. File interaction will anyway slow down the simulation.
